Deb repo maker
tradingview/jewel-case pull request #5
Opened 2023-06-02 14:53 UTC by origin-yaropolk

2023-06-26 08:00 UTC, Nipheris requested changes

2023-06-26 08:00 UTC, Nipheris commented on src/http.mts
> +export function get(url: string, opt: {stream: boolean} = { stream: false }): Promise<Buffer | Readable> {
Better to have separate functions for stream and buffer responses, no common logic shared here.

2023-06-26 08:00 UTC, Nipheris commented on src/jfrog/jfrog-artifacts-provider.mts
> +	public createMetapointerFile(artifact: Artifact, fileName: string): void {
This is more about `s3-groundskeeper`, not Artifactory. I think we should have this in a separate module (and we already have the similar logic in `deb-builder`)

2023-06-26 08:00 UTC, Nipheris commented on src/deb/deb-builder.mts
> +	}[] = [];
We need a separate type for array item here.

2023-06-26 08:00 UTC, Nipheris commented on src/deb/deb-builder.mts
> +		this.pool = `${this.config.base.out}/repo/${this.config.debBuilder.applicationName}/deb/pool`;
Also use `path.join` to build a path?

2023-06-26 08:00 UTC, Nipheris commented on src/ibuilder.mts
> +export interface IBuilder {
What about `Deployer`? And without `I` 😁

2023-06-26 08:00 UTC, Nipheris commented on src/jfrog/jfrog-artifacts-provider.mts
Rename to `artifacts-provider`, `jfrog` looks a bit excessive.

2023-06-26 08:00 UTC, Nipheris commented on src/jfrog/jfrog-artifacts-provider.mts
> +export class JfrogArtifactsProvider implements ArtifactsProvider {
What about default export?

2023-06-26 08:00 UTC, Nipheris commented on src/jfrog/jfrog-artifacts-provider.mts
> +			const buildInfoEndpoint = `${buildsEndpoint}/${buildNumber}?started=${value.toISOString()}`;
What about using [`URL`](https://nodejs.org/api/url.html) class for this purpose?

2024-02-06 20:36 UTC, Nipheris requested changes

2024-02-06 20:36 UTC, Nipheris commented on src/artifacts-provider.mts
> +export interface ArtifactsProvider {
It is more correct to use `ArtifactProvider`, note the singular form, like [here](https://opennlp.apache.org/docs/1.8.2/apidocs/opennlp-tools/opennlp/tools/util/model/ArtifactProvider.html).

2024-02-06 20:36 UTC, Nipheris commented on src/config.mts
> +export type Config = BaseConfig & DebBuilderConfig & ArtifactsProviderConfig;
I think you messed up with nesting here.
I think it should be `interface BaseConfig { out: string; repo: Repo; }` and `interface Config = { base: BaseConfig; ... }`, and the same applies to other subobjects of Config.

2024-02-06 20:36 UTC, Nipheris commented on src/artifacts-provider-config.mts
> +	artifactsProvider: {
This inner object should be described by `ArtifactsProviderConfig` I think.

2024-02-06 20:36 UTC, Nipheris commented on package.json
> +		"s3-groundskeeper": "0.2.2",
Почему dev-зависимость?

2024-02-06 20:36 UTC, Nipheris commented on src/artifacts-provider-config.mts
> +		type: ProviderType,
The other fields are about Artifactory, not about every artifact provider in general, so I suggest moving them to a separate type, and define `ArtifactsProviderConfig` as a union type with different configuration types as union members.

Btw, this "separate type" could be placed in `jfrog/artifacts-provider.mts`, that sounds reasonable to me.

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +	private debName(version: string, arch: string): string {
`debName` is a bit ambiguous, why not `debFileName`?

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder-config.mts
> +export interface DebBuilderConfig {
Why this type is not called just `Config`, as soon as it is located in `deb/deb-builder`?

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +export class DebBuilder implements Deployer {
I would call it `DebianRepositoryBuilder` or `DebRepoBuilder` to keep it short, and the file should be `deb/repo-builder`  or `deb/repository-builder`. And this class looks like a good candidate for default export.
And why not `DebianRepositoryDeployer`? Later it could use some generic "file deployer" to deploy repo contents to AWS S3, passed to it's constructor

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +		const publicKeyPath = path.join(this.keys, 'desktop.asc');
Where is this key file coming from? Should we move the path to config?

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +	private readonly pool: string;
I prefer adding `Path` in the names of such fields, like `poolPath`, `distsPath`, `keysPath`.

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +		this.pool = path.join(this.config.base.out, 'repo', this.config.debBuilder.applicationName, 'deb', 'pool');
Let's try to pass the "working directory" of a SPECIFIC deployer, effectively making it subdirectory of `out` or just making it a part of deployer configuration.

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +		const cocntrolTarSize = Number((await requestRange(debUrl, controlTarSizeRange)).read().toString()
Why not use `parse*` functions? And there is a typo in constant name.

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +					const repoRoot = path.join(this.config.base.out, 'repo', this.config.debBuilder.applicationName, 'deb');
One more place to use repo root path prepared in constructor and stored in some readonly field.

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +		const whereExtract = path.join(os.tmpdir(), `control-${crypto.randomBytes(4).toString('hex')}`);
It looks like we already have a working directory for the deployer. Why not use it for this purpose and leave TEMP untouched?

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +					const controlMetaContent = fs.readFileSync(path.join(whereExtract, 'control'), 'utf-8').replaceAll(':', '=');
Hah, using INI parser just by replacing `:` to `=` looks dangerous.. But ok, let's move one with this implementation now.

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +					fs.appendFile(targetMetaPath, dataToAppend, err => {
Try to use `node:fs/promises`

2024-02-06 20:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +						channel,
Better call this `distribution` is Debian repo context. It is up to user configuration to decide what distributions correspond to "channels", like we call them in Windows/macOS repo.

2024-02-16 13:55 UTC, origin-yaropolk commented on src/deb/deb-builder.mts
> +					const controlMetaContent = fs.readFileSync(path.join(whereExtract, 'control'), 'utf-8').replaceAll(':', '=');
¯\_(ツ)_/¯

2024-03-15 12:16 UTC, Nipheris requested changes
And dont forget to fix the tests after config refactoring we discussed 😀

2024-03-15 12:16 UTC, Nipheris commented on src/s3-metapointer.mts
> +export default function metapointerContent(fileMd5Hash: string): string {
I think non-default function called `content` would be better.
`import { content as metapointerContent } from '../s3-metapointer.mjs';`

2024-03-15 12:16 UTC, Nipheris commented on src/fs.mts
> +export function createMetapointerContent(fileMd5Hash: string): string {
Are we calling this function somewhere?

2024-03-15 12:16 UTC, Nipheris commented on src/http.mts
> +export function requestStream(url: string, method: string, requestData?: RequestData): Promise<IncomingMessage> {
Could we use `URL` type instead of `string` where possible? Like we do in [s3-groundskeeper](https://github.com/tradingview/s3-groundskeeper/pull/10/commits/81d5557386f254a2c0d87f1cec034dc535173b2a).

2024-03-15 12:16 UTC, Nipheris commented on src/jfrog/artifact-provider.mts
> +	public createMetapointerFile(artifact: Artifact, fileName: string): void {
This method is not related to `jfrog/artifact-provider` and could be an exported function in `s3-metapointer.mts` instead. `metapointer` is a concept from `s3-groundskeeper`, not from Artifactory.

2024-03-15 12:48 UTC, origin-yaropolk commented on src/fs.mts
> +export function createMetapointerContent(fileMd5Hash: string): string {
not yet

2024-03-25 21:36 UTC, Nipheris commented on src/deb/deb-builder.mts
> +	private debName(version: string, arch: string): string {
efcba511bf60c48982753581132f2f3aba5216d9

2024-03-25 21:37 UTC, Nipheris commented on src/deb/deb-builder.mts
> +	private debName(version: string, arch: string): string {
efcba511bf60c48982753581132f2f3aba5216d9

2024-03-25 21:38 UTC, Nipheris commented on src/deb/deb-builder.mts
> +	private readonly pool: string;
01fa12bf1850a1bb48a1f9d79b4bf13c784f14bb

2024-03-25 21:38 UTC, Nipheris commented on src/deb/deb-builder.mts
> +		const cocntrolTarSize = Number((await requestRange(debUrl, controlTarSizeRange)).read().toString()
435e0121c11d2368508c132bdec0ca2d2897ffe1

2024-03-27 03:16 UTC, Nipheris approved these changes

2024-03-27 03:22 UTC, merged